### ISSUE TITLE
nothing happen after i click on generate button

### ISSUE THREAD

**Issue by Fshamri** [misakuo/svgtoandroid#1]
i have installed this plugin on android studio 1.5.1 but nothing happen after i click on generate button. seems the button is not functioning

**Comment by misakuo** [comment]
Hi, could you provide the content of SVG file and the message on Event Log?

**Comment by misakuo** [comment]
Hi, the latest update was fixed this issue, you can update plugin from repo and resolving problem.thanks for your report.
