### ISSUE TITLE
AI 导出的svg，导入后颜色丢失

### ISSUE THREAD

**Issue by ittianyu** [misakuo/svgtoandroid#17]

**Comment by misakuo** [comment]
请提供原始的svg文件内容

**Comment by ittianyu** [comment]
[logo](http://og3oqobbi.bkt.clouddn.com/logo.svg)

**Comment by misakuo** [comment]
找到原因了，AI导出的svg将颜色属性放到了style里，插件目前没有对这一块进行解析，后续会做支持。

**Comment by misakuo** [comment]
顺便提一句，你提供的这个svg文件冗余图层比较多，可能会有性能问题。并且图案边缘也不是很光滑。

**Comment by ittianyu** [comment]
多谢提醒

**Comment by misakuo** [comment]
1.6版本已修复该问题，插件正在审核流程中。
