### ISSUE TITLE
Converting from polygon with points

### ISSUE THREAD

**Issue by rbloomdaleIXL** [misakuo/svgtoandroid#18]
There is a bug where if converting from a polygon in the form
`<polygon points="0 0 0 100 100 100 100 0 0 0" fill="#0000FF"/>`
results in an invalid vector path of the form
`<path
    android:fillColor="#0000FF"
    android:pathData="M0 L0 L0 L100 L100 L100 L100 L0 L0 L0 z" />`
where it should be
`<path
    android:fillColor="#0000FF"
    android:pathData="M0,0 L0,100 L100,100 L100,0 L0,0 z" />`

**Comment by misakuo** [comment]
welcome to pull request for this issue, the code is [here](https://github.com/misakuo/svgtoandroid/blob/master/src/com/moxun/s2v/utils/SVGAttrParser.java#L40)

**Comment by misakuo** [comment]
Please update to version 1.6.1

**Comment by rbloomdaleIXL** [comment]
Thank you. Especially for being so quick
