### ISSUE TITLE
Improve format of generated resource

### ISSUE THREAD

**Issue by igorwojda** [misakuo/svgtoandroid#19]
Two things that can be improved

1. OrderOfAttributes - pathData attribute can sometimes take be long so I thing it should be placed  at the end of attributes list (now for ex it's difficult to change color without scrolling all the way right)
![orderofattributes](https://cloud.githubusercontent.com/assets/530122/23958765/0791b196-099b-11e7-9f77-12bd70381019.png)

2. PreformatedCode (each attribute in new line)
![preformatedcode](https://cloud.githubusercontent.com/assets/530122/23958769/0984b282-099b-11e7-922f-b3441f0bd49a.png)

**Comment by misakuo** [comment]
Thanks for your feedback, I think order of attributes is more viable, the generated source will be reformatted according to the default configuration by plugin, so, each attribute in new line might be more difficult to achieve.
I will release a new version with the attribute ordering features as soon as possible

**Comment by misakuo** [comment]
The newest version 1.6.2 could be work well

**Comment by igorwojda** [comment]
I have noticed that running format code command and changes order of the attributes (and also format it properly), so maybe you could simply run  it it on newly generated file

**Comment by misakuo** [comment]
Unfortunately, the behavior between reformat code command and  invoking `CodeStyleManager#reformat()` method  is different, so could not reformat xml on code as your expect, it also bothered me :(

**Comment by igorwojda** [comment]
I assume you did proper research on this, so if it's not possible, just close this ussie.

Thanks for fix ;-)

**Comment by misakuo** [comment]
I will continue to try to solve this problem, thanks for your feedback again.
