### ISSUE TITLE
it's not work. please fixed plugin..

### ISSUE THREAD

**Issue by lmklmk99** [misakuo/svgtoandroid#2]
hi  

installed plugin my Android studio. after i try convert SVG file. i clicked "Generate" button when, "Event log" window show error message : 

Plugin Error: SVG2VectorDrawable threw an uncaught NoSuchMethodError. Disable Plugin
NoSuchMethodError: com.intellij.ide.fileTemplates.FileTemplateManager.findInternalTemplate(Ljava/lang/String;)Lcom/intellij/ide/fileTemplates/FileTemplate;

so i report issue for you.

please fixed bug. thank you.

**Comment by misakuo** [comment]
Hi,could you provide the version about your Android Studio?

**Comment by lmklmk99** [comment]
i used Android Studio 1.5.1.  and Mac OS X.

**Comment by misakuo** [comment]
OK, I am reappear the same bug on Android Studio 1.5.1, bug fix will as soon as possible.

**Comment by misakuo** [comment]
Hi, 
The reason is the method 'findInternalTemplate' not supported by older Android Studio, the latest update was fixed this issue, you can update plugin from repo now. thanks for your report.
