### ISSUE TITLE
转换后透明度丢失

### ISSUE THREAD

**Issue by dongweiq** [misakuo/svgtoandroid#23]
svg图片可以设置一些图层的透明度，转换后不透明的没有问题，有透明度的就变成了黑色😂

**Comment by misakuo** [comment]
麻烦提供一下原始的svg内容：）

**Comment by dongweiq** [comment]
[svg_icon.zip](https://github.com/misakuo/svgtoandroid/files/963728/svg_icon.zip)

**Comment by misakuo** [comment]
插件没有处理`opacity`属性，后面归类到`fill-opacity`一起处理下就ok了
