### ISSUE TITLE
转换后样式出问题，

### ISSUE THREAD

**Issue by hnlbxb2004** [misakuo/svgtoandroid#4]
这个是Sketch 导出的svg ，转换后，样子不正确。 下面的格式不争气，不可以复制到一个文件里面实验一下。

`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg width="160px" height="160px" viewBox="0 0 160 160" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    
    <title>694D04A6-7A7B-43D3-9F79-461149F5D174</title>
    <desc>Created with sketchtool.</desc>
    <defs>
        <path d="M19.6666667,71.25 C30.022,71.25 38.4166667,62.8553333 38.4166667,52.5 L38.4166667,18.75 C38.4166667,8.39466667 30.022,0 19.6666667,0 C9.31133333,0 0.916666667,8.39466667 0.916666667,18.75 L0.916666667,52.5 C0.916666667,62.8553333 9.31133333,71.25 19.6666667,71.25 L19.6666667,71.25 Z" id="path-1"></path>
    </defs>
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="1024-copy" transform="translate(-709.000000, -18.000000)">
            <g id="noun_401925_cc-copy-2" transform="translate(709.000000, 18.000000)">
                <g id="Group" transform="translate(46.000000, 20.000000)">
                    <g id="Rectangle-54" transform="translate(15.000000, 0.000000)">
                        <mask id="mask-2" fill="white">
                            <use xlink:href="#path-1"></use>
                        </mask>
                        <use id="Mask" fill="#FFFFFF" xlink:href="#path-1"></use>
                        <rect fill="#67E36C" mask="url(#mask-2)" x="2" y="59" width="36" height="15"></rect>
                    </g>
                    <path d="M30.9166667,86.0377333 L30.9166667,112.5 L8.41666667,112.5 L8.41666667,120 L30.9166667,120 L38.4166667,120 L60.9166667,120 L60.9166667,112.5 L38.4166667,112.5 L38.4166667,86.0377333 C55.2906667,84.1714667 68.4166667,69.8713333 68.4166667,52.5 L60.9166667,52.5 C60.9166667,66.9974667 49.1641333,78.75 34.6666667,78.75 C20.1692,78.75 8.41666667,66.9974667 8.41666667,52.5 L0.916666667,52.5 C0.916666667,69.8714667 14.0426667,84.1716 30.9166667,86.0377333 L30.9166667,86.0377333 Z" id="Shape" fill="#FFFFFF"></path>
                </g>
            </g>
        </g>
    </g>
</svg>`

**Comment by misakuo** [comment]
这是转换前的SVG(为了能看清边缘我把颜色改成了绿色)  
![before](http://ww4.sinaimg.cn/mw690/9000c060gw1f3rlafj7a5j206u070q2u.jpg)
这是转换后的xml  
![after](http://ww4.sinaimg.cn/mw690/9000c060gw1f3rlaeurl6j20be0agjrg.jpg)  
下面是转换出的xml内容    

```
<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android" android:viewportWidth="160"
    android:viewportHeight="160" android:width="160dp" android:height="160dp">
    <group android:name="Group" android:translateX="46.000000" android:translateY="20.000000">
        <path android:name="Shape"
            android:pathData="M30.9166667,86.0377333 L30.9166667,112.5 L8.41666667,112.5 L8.41666667,120 L30.9166667,120 L38.4166667,120 L60.9166667,120 L60.9166667,112.5 L38.4166667,112.5 L38.4166667,86.0377333 C55.2906667,84.1714667 68.4166667,69.8713333 68.4166667,52.5 L60.9166667,52.5 C60.9166667,66.9974667 49.1641333,78.75 34.6666667,78.75 C20.1692,78.75 8.41666667,66.9974667 8.41666667,52.5 L0.916666667,52.5 C0.916666667,69.8714667 14.0426667,84.1716 30.9166667,86.0377333 L30.9166667,86.0377333 Z"
            android:fillColor="#FFFFFF" />
        <group android:name="Rectangle-54" android:translateX="15.000000"
            android:translateY="0.000000">
            <path android:pathData="M2,59L38,59L38,74L2,74z" android:fillColor="#67E36C" />
        </group>
    </group>
</vector>
```

问题主要有两点：  
1. Android的VectorDrawable目前并不支持`<mask>`标签，所以源svg里的遮罩在转换后丢失了，对于这个问题，可以在定义图案的时候直接用path描述，避免使用遮罩层  
2. 转换出的path顺序和期待的顺序反了（绿色矩形）应该被放在外面弧线的下方，这个是bug，后续会修复
