### ISSUE TITLE
AS 3.4 上不显示插件入口

### ISSUE THREAD

**Issue by xiaoGuy** [misakuo/svgtoandroid#44]
在 AS 3.4 上安装插件后，不会在界面上显示插件的按钮，无法使用了

**Comment by chenyusheng** [comment]
我也是遇到这个问题，As版本是3.4.1

**Comment by littlecorgi-twk** [comment]
AS 3.4.2 也有这个问题

**Comment by misakuo** [comment]
我抽时间看下，工作太忙，疏于维护，不好意思

**Comment by misakuo** [comment]
各位是什么平台上？我Mac OS上是OK的

**Comment by misakuo** [comment]
IDE启动的时候有没有插件相关的Error或Warning信息报出？

**Comment by misakuo** [comment]
可以通过 Generate 快捷键唤起插件，工具栏按钮只是入口之一
