### ISSUE TITLE
Output name of file is incorrect in some cases (filenames with numbers?)

### ISSUE THREAD

**Issue by chris-dura** [misakuo/svgtoandroid#46]
I used your tool to batch process a bunch of SVGs. A few of the SVGs were output with extra underscores in their filenames.

`ki-a11y.svg` was output as `vector_drawable_ki_a__y.svg`
`ki-a11y-f.svg` was output as `vector_drawable_ki_a__y_f.svg`

So, your tool definitely didn't like using `11` in the filename...

**Comment by misakuo** [comment]
Please update the plugin to version 1.8.2, thanks for your feedback.
