### ISSUE TITLE
How to access the plugin, what does "Click ..." means in README?

### ISSUE THREAD

**Issue by romanr** [misakuo/svgtoandroid#47]
what does "Click `...`" means in README? Click `...` where? There's no `...` anywhere. Is it in menu, in project tree? I can't find anywhere. 🤷‍♂

**Comment by misakuo** [comment]
There has an issue with Android Studio 3.6.1, I will fix it ASAP

**Comment by misakuo** [comment]
Please update the plugin to version 1.8.2, thanks for your feedback
