### ISSUE TITLE
我想问的是,在IDEA里装好插件,怎么打开那个例子里的转换窗口...

### ISSUE THREAD

**Issue by seakingii** [misakuo/svgtoandroid#5]
找不到地方可以打开.我用的是WINDOWS版本的 IDEA 2016.1.3

**Comment by misakuo** [comment]
安装完成并重启之后，Toolbar上应该会有![icon](https://raw.githubusercontent.com/misakuo/svgtoandroid/master/src/icons/icon_new.png)这样一个图标，看不到入口的原因可能是你没有显示Toolbar

**Comment by seakingii** [comment]
你好,按照你的提示,已找到这个图标.
