### ISSUE TITLE
未适配AndroidStudio4.1

### ISSUE THREAD

**Issue by nszaaa3** [misakuo/svgtoandroid#54]
插件版本：1.8.2
AndroidStudio版本： 4.1
打开Studio提示Plugin "SVG2VectorDrawable" is incompatible (supported only in IntelliJ IDEA).

**Comment by woxingxiao** [comment]
> 插件版本：1.8.2
> AndroidStudio版本： 4.1
> 打开Studio提示Plugin "SVG2VectorDrawable" is incompatible (supported only in IntelliJ IDEA).

附议！请作者大神抽空解决下 @misakuo

**Comment by fanzhouyou** [comment]
+1

**Comment by misakuo** [comment]
有点看不懂我自己的代码了，我抽时间处理下：）

**Comment by misakuo** [comment]
Hi all, 请更新到1.8.3版本
