### ISSUE TITLE
1.9.0版本在Androidstudio 4.0.1与 4.1.1上均无法正确转换，得到的xml文件是空的

### ISSUE THREAD

**Issue by tingfngy** [misakuo/svgtoandroid#59]
1.9.0版本在Androidstudio 4.0.1与 4.1.1上均无法正确转换，可以生成对应的xml文件，但是文件内没有任何内容。

**Comment by tingfngy** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<svg width="104px" height="104px" viewBox="0 0 104 104" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <title>icon_newUser_03_dark</title>
    <defs>
        <linearGradient x1="73.9785513%" y1="76.0290642%" x2="19.1982331%" y2="11.6116495%" id="linearGradient-1">
            <stop stop-color="#FA3B32" stop-opacity="0" offset="0%"></stop>
            <stop stop-color="#FA3B32" offset="100%"></stop>
        </linearGradient>
    </defs>
    <g id="标签-夜间" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="图标svg" transform="translate(-504.000000, -288.000000)">
            <g id="icon_newUser_03_dark" transform="translate(504.000000, 288.000000)">
                <rect id="矩形" x="0" y="0" width="104" height="104"></rect>
                <circle id="椭圆形" fill="url(#linearGradient-1)" opacity="0.699999988" cx="69.6333333" cy="42.6333333" r="18.6333333"></circle>
                <path d="M49.0001638,55.5 C53.4323787,55.5 57.8661496,55.7476535 62.3024587,56.2427334 C69.7956755,57.0801955 75.5,63.0257386 75.5,70.1667755 C75.5,76.9490111 69.6391684,82.363636 62.5040437,82.363636 L62.5040437,82.363636 L35.4959563,82.363636 C28.3608316,82.363636 22.5,76.9490111 22.5,70.1667755 C22.5,63.0256947 28.2040498,57.0801896 35.6968155,56.2427779 C40.1110667,55.748713 44.5534048,55.5006755 49.0001638,55.5 Z M49.0005436,60.5 C44.7396783,60.5006473 40.4827582,60.7383319 36.2525696,61.2117957 C31.2186743,61.7743974 27.5,65.6504851 27.5,70.1667755 C27.5,74.0952732 31.037701,77.363636 35.4959563,77.363636 L35.4959563,77.363636 L62.5040437,77.363636 C66.962299,77.363636 70.5,74.0952732 70.5,70.1667755 C70.5,65.6505775 66.7810917,61.7744078 61.7475088,61.211841 C57.4953604,60.7373129 53.2467174,60.5 49.0005436,60.5 Z M49.0002526,21.5 L49.3210534,21.5030582 C58.2856743,21.6740612 65.5,28.9946615 65.5,38.0001534 C65.5,47.1129237 58.1128119,54.5 49.0001534,54.5 C39.8874948,54.5 32.5,47.112617 32.5,37.9998466 C32.5,28.8871156 39.8874772,21.4996385 49.0002526,21.5 L49.0002526,21.5 Z M49.0000542,26.5 C42.6488244,26.499748 37.5,31.6485724 37.5,37.9998466 C37.5,44.3511763 42.6489016,49.5 49.0001534,49.5 C55.3514051,49.5 60.5,44.3514831 60.5,38.0001534 C60.5,31.6488262 55.3514076,26.5 49.0000542,26.5 Z" id="形状结合" fill="#D2D2D3" fill-rule="nonzero"></path>
            </g>
        </g>
    </g>
</svg>

**Comment by Quenstin** [comment]
mac 电脑好像可以

**Comment by xingyuSun** [comment]
有没有解决方案呢？

**Comment by tingfngy** [comment]
> 有没有解决方案呢？

我查到的这个问题的原因是：在windows上，文件的换行符是CRLF，用这个换行符的字符串就会解析失败。解决方案也很简单，自己加一行代码换一下换行符。

**Comment by sswukang** [comment]
> 有没有解决方案呢？

下载上个版本的，然后本地离线安装。

**Comment by misakuo** [comment]
请更新到最新的1.9.2版本，已经在win系统上验证过可行
之前给issue里其他反馈的用户打包了1.9.1版本解决了这个问题，忘记上传到marketplace了，sorry
