### ISSUE TITLE
NullPointerException: null

### ISSUE THREAD

**Issue by imyyq-star** [misakuo/svgtoandroid#7]
AndroidStudio：2.1.3
系统：windows 7 64 旗舰版
SVGToAndroid版本：2.4.3

不管用，不管怎么选选项，都没用，在Event Log报错如题

**Comment by misakuo** [comment]
麻烦把出错的StackTrace提供一下

**Comment by misakuo** [comment]
麻烦更新到1.4.6版本试试 😄
