### ISSUE TITLE
在android studio 2.1.3中無法正確辨識android專案

### ISSUE THREAD

**Issue by yoyo930021** [misakuo/svgtoandroid#8]
module 無法選擇 或輸入
直接執行 會說不是正確的android專案

**Comment by misakuo** [comment]
您好，请问是提示“Current project is not an Android project!”么？
如果是的话，导致这个问题的原因是插件判断IDE当前打开的Project不是一个正确的Android Project，该判断逻辑位于`ModulesUtil.isAndroidProject`方法内，简单来说就是判断当前Project的根目录下有没有`build.gradle`文件，如果有的话则视为一个合法的Android Project。Module相关的判断逻辑也在这个文件内，您可以根据自己Project的实际情况对插件逻辑进行一些修改，或者提供您出问题的Project的目录结构给我我来看一下是否是插件逻辑的问题 😄

**Comment by yoyo930021** [comment]
已找到問題 
我的project 
build.gradle 被命名為setting.gradle
